export const NEXT_LAYER = 'NEXT_LAYER'
export const PREVIOUS_LAYER = 'PREVIOUS_LAYER'
export const SET_FIRST_LAYER = 'SET_FIRST_LAYER'
export const SET_VALUE_LAYER = 'SET_VALUE_LAYER'

export const ADD_STATUSES_TO_SELECTS = 'ADD_STATUSES_TO_SELECTS'
export const REMOVE_STATUSES_FROM_SELECTS = 'REMOVE_STATUSES_FROM_SELECTS'
export const SET_STATUSES = 'SET_STATUSES'

export const SET_CATEGORY = 'SET_CATEGORY'

export const GET_LABELS_SPEC = 'GET_LABELS_SPEC'
export const SET_SPECS_LABEL_ITEM = 'SET_SPECS_LABEL_ITEM'
export const ADD_SPECIFICATION_ITEM = 'ADD_SPECIFICATION_ITEM'
export const REMOVE_SPECIFICATION_ITEM = 'REMOVE_SPECIFICATION_ITEM'
export const SET_SPECIFICATION_SEARCHES = 'SET_SPECIFICATION_SEARCHES'

export const ADD_DATE_RANGE = 'ADD_DATE_RANGE'
export const DELETE_DATE_RANGE = 'DELETE_DATE_RANGE'

export const GET_REPORT = 'GET_REPORT'
export const SET_REPORT_GRAPH_TYPE = 'SET_REPORT_GRAPH_TYPE'
export const DOWNLOAD_REPORT = 'DOWNLOAD_REPORT'

export const SET_AND_SEARCH = 'SET_AND_SEARCH' // ?





