export const NEXT_LAYER = 'NEXT_LAYER'
export const PREVIOUS_LAYER = 'PREVIOUS_LAYER'
export const SET_FIRST_LAYER = 'SET_FIRST_LAYER'
export const SET_VALUE_LAYER = 'SET_VALUE_LAYER'

export const ADD_STATUSES_TO_SELECTS = 'ADD_STATUSES_TO_SELECTS'
export const REMOVE_STATUSES_FROM_SELECTS = 'REMOVE_STATUSES_FROM_SELECTS'
export const SET_STATUSES = 'SET_STATUSES'

export const SET_CATEGORY_SUB_ITEM = 'SET_CATEGORY_SUB_ITEM'
export const ADD_CATEGORY_ITEM = 'ADD_CATEGORY_ITEM'
export const REMOVE_CATEGORY_ITEM = 'REMOVE_CATEGORY_ITEM'
export const SET_CATEGORY_SEARCHES = 'SET_CATEGORY_SEARCHES'

export const ADD_DATE_RANGE = 'ADD_DATE_RANGE'
export const DELETE_DATE_RANGE = 'DELETE_DATE_RANGE'

export const SET_REPORT_VIEW = 'SET_REPORT_VIEW'
export const SET_REPORT_STATISTIC_LISTS = 'SET_REPORT_STATISTIC_LISTS'
export const SET_REPORT_CHART_TYPE = 'SET_REPORT_CHART_TYPE'
export const SET_REPORT = 'SET_REPORT'
export const CHANGE_REPORT_LAYER_STATUS = 'CHANGE_REPORT_LAYER_STATUS'



